sudo: required
services:
  - docker
before_install:
  - docker build -t deniurchak/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true deniurchak/docker-react npm run test -- --coverage
language: generic 